name: model-server
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - flask=1.0.2
  - requests=2.22.0
  - numpy=1.16.3
  - pandas=0.24.2
  - scikit-learn=0.20.3
  - scipy=1.3.0
  - astropy=3.2.1
  - tensorflow=1.13.1
  - keras=2.2.5
  - xgboost=0.90