FROM c12e/certifai-reference-models-server:latest

LABEL  release=1 \
       name="cortex-certifai-reference-models" \
       vendor="CognitiveScale" \
       version=1 \
       summary="Cortex Certifai Reference Model Server" \
       description="Cortex Certifai Reference Model Server for RedHat OpenShift" \
       com.cognitivescale.license_terms="https://www.cognitivescale.com/legal-information/" 

