from logisticRegression.predict import predict_german_credit_logit
from decisionTree.predict import predict_german_credit_dtree
from multiLayerPerceptron.predict import predict_german_credit_mlp
from supportVectorMachine.predict import predict_german_credit_svm

