from insurance_auto_insurance_claims.linearRegressionL1.predict import predict_auto_insurance_linl1
from insurance_auto_insurance_claims.linearRegressionL2.predict import predict_auto_insurance_linl2
from insurance_auto_insurance_claims.randomForest.predict import predict_auto_insurance_rf
from insurance_auto_insurance_claims.neuralNetwork.predict import predict_auto_insurance_nn
from insurance_auto_insurance_claims.supportVectorRegression.predict import predict_auto_insurance_svr